package ca.uwaterloo.cs

enum class PageStates {
    WELCOME, LOGIN, SIGNUP_STEP1, SIGNUP_STEP2, SIGNUP_STEP3,
    SIGNUP_CLOUD, SIGNUP_CLOUD_MORE, SIGNUP_AFFIRMATION, SIGNUP_PIN,
    HOME,
    AFFIRMATION,
    JOURNAL_STEP1, JOURNAL_STEP2, JOURNAL_STEP3, PAST_JOURNAL,
    MEDITATE,
    PHOTOBOOK,
    SETTINGS
}

enum class InputErrorStates {
    NONE,
    EMPTY_INPUT,
    INVALID_EMAIL,
    INVALID_PASSWORD
}
